name: ci

on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up for image building
        uses: docker/setup-buildx-action@v2
      # https://github.com/marketplace/actions/docker-login
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: xihh86/awscli-v2:${{ github.sha }}
